---
- hosts: "hostname"
  become: true
  become_method: sudo

  tasks:
    - name: Create a 2048-bit SSH key for user jsmith in ~jsmith/.ssh/id_rsa
      ansible.builtin.user:
        name: johnd
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: .ssh/id_rsa