apiVersion: apps/v1
kind: Deployment
Namespace: gaston-mdruart
metadata:     
  name: apache2 
  labels:
     app: apache2  
spec:
  replicas: 2  
  selector:
    matchLabels:
      app: apache2
  template:
    metadata:
      labels:
        app: apache2
    spec:
      containers:
      - name: apache2
        image: httpd:bullseye
        ports:
        - containerPort: 80
